#!/bin/sh

test -d interfaces || mkdir interfaces
test -d interfaces/cc || mkdir interfaces/cc
perl auto/mk-src.pl

bunzip2 -c data.tar.bz2 | tar x -f-
test -d inst/lib || mkdir inst/lib
test -d inst/lib/pspell || mkdir inst/lib/pspell

libtoolize --automake || exit 1
aclocal || exit 1
autoheader || exit 1
automake --add-missing --foreign || exit 1
autoconf || exit 1

