#!/bin/sh

test -d interfaces || mkdir interfaces
test -d interfaces/cc || mkdir interfaces/cc
cd auto/
perl mk-src.pl
perl mk-doc.pl
touch auto
cd ..

cd manual
test -e man-html || mkdir man-html
test -e man-text || mkdir man-text
test -e dev-html || mkdir dev-html
test -e dev-text || mkdir dev-text
touch man-html/manual.html man-text/manual.txt
touch dev-html/devel.html dev-text/devel.txt
cd ..

autopoint -f || exit 1
libtoolize --automake || exit 1
aclocal -I m4 $ACLOCAL_FLAGS || exit 1
autoheader || exit 1
automake --add-missing --foreign || exit 1
autoconf || exit 1

